# update-deps.yml
name: "Run Gofmt and Goimport"
description: "Automatic golang formatting and import ordering"
branding:
  icon: pen-tool
  color: green
outputs:
  create_pr:
    description: "Whether a PR should be created because there were meaningful changes"
  deplog:
    description: "Report on module changes"
runs:
  using: 'docker'
  image: 'Dockerfile'
