# update-deps.yml
name: "Update Go Deps and Codegen"
description: "Updates golang dependencies and codegen using using hack/update-deps.sh and hack/update-codegen.sh"
branding:
  icon: download-cloud
  color: green
inputs:
  release:
    description: "Release? (vX.Y) defaults to current release"
  pr-empty-deps:
    description: "If true, send update PRs even for deps changes that don't change vendor. Defaults to false to reduce no-op PR spam."
outputs:
  create_pr:
    description: "Whether a PR should be created because there were meaningful changes"
  deplog:
    description: "Report on module changes"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RELEASE: ${{ inputs.release }}
    FORCE_DEPS: ${{ inputs.pr-empty-deps }}
