# update-deps.yml
name: "Fix Misspellings"
description: "Automatic spelling correction"
branding:
  icon: pen-tool
  color: green
outputs:
  create_pr:
    description: "Whether a PR should be created because there were meaningful changes"
  deplog:
    description: "Report on spelling changes"
runs:
  using: 'docker'
  image: 'Dockerfile'
