# update-deps.yml
name: "Update community"
description: "Update community files such as OWNERS_ALIASES"
branding:
  icon: users
  color: green
outputs:
  create_pr:
    description: "Whether a PR should be created because there were meaningful changes"
  log:
    description: "Log of changes"
runs:
  using: 'docker'
  image: 'Dockerfile'
