# update-deps.yml
name: "Update actions"
description: "Update GitHub actions"
branding:
  icon: refresh-ccw
  color: green
inputs:
  organization:
    description: 'The organization that the actions should be copied for.'
  repo:
    description: 'The repo being copied to, for repo-specific customizations.'
outputs:
  create_pr:
    description: "Whether a PR should be created because there were meaningful changes"
  log:
    description: "Log of changes"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ORGANIZATION: ${{matrix.meta-organization}}
    REPO: ${{matrix.name}}